### PR TITLE
Definition is loaded from loacalhost 

### PR DESCRIPTION
**Pull request by Abd-ulRahman**
All you have to do is run Apache and place the latest definition folder in hotdocs
Tested and working
for your kind information the save button is not working on adding new record
On the other hand Save as does it
Done

### CODE REVIEW

**Comment by Abd-ulRahman** [comment]
You may check my db2 viewer at
https://github.com/Abd-ulRahman/db2

**Comment by KalopsiaTwilight** [comment]
Hi!

Thanks for the PR, but I don't think this is functionality that I need or foresee other people needing in the future. 
Best of luck with your fork though! :)

**Comment by Greyisttot** [comment]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DBFileReaderLib.Writers.WDC3RowSerializer`1.Serialize(Int32 id, T row) in C:\GitHub\WDBXEditor2\DBFileReaderLib\Writers\WDC3Writer.cs:line 43
   at DBFileReaderLib.Writers.WDC3RowSerializer`1.Serialize(IDictionary`2 rows) in C:\GitHub\WDBXEditor2\DBFileReaderLib\Writers\WDC3Writer.cs:line 38
   at DBFileReaderLib.Writers.WDC3Writer`1..ctor(WDC3Reader reader, IDictionary`2 storage, Stream stream) in C:\GitHub\WDBXEditor2\DBFileReaderLib\Writers\WDC3Writer.cs:line 303
   at DBFileReaderLib.DBParser.WriteRecords[T](IDictionary`2 storage, Stream stream) in C:\GitHub\WDBXEditor2\DBFileReaderLib\DBParser.cs:line 121
   at DBFileReaderLib.DBParser.WriteRecords[T](IDictionary`2 storage, String filename) in C:\GitHub\WDBXEditor2\DBFileReaderLib\DBParser.cs:line 114
   at DBFileReaderLib.Storage`1.Save(String fileName) in C:\GitHub\WDBXEditor2\DBFileReaderLib\Storage.cs:line 22
   at DBCD.DBCDStorage`1.Save(String filename) in C:\GitHub\WDBXEditor2\DBCD\DBCDStorage.cs:line 142
   at WDBXEditor2.MainWindow.Save_Click(Object sender, RoutedEventArgs e) in C:\GitHub\WDBXEditor2\WDBXEditor2\MainWindow.xaml.cs:line 146
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Pull request closed without merging**
